on:
  push:
    branches: ["main"]
    paths:
      - "src/**/*.cs"
      - "src/**/*.csproj"
  pull_request:
    paths:
      - "src/**/*.cs"
      - "src/**/*.csproj"

name: Build

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Run build
        run: dotnet build --configuration Release

      - name: Upload repl
        uses: actions/upload-artifact@v6
        with:
          name: Yilduz.Repl_net8.0
          path: src/Yilduz.Repl/bin/Release/net8.0/
